VIBE_VERSION_MAJOR := 1
VIBE_VERSION_MINOR := 0

VIBE_BUILD_DATE := $(shell date -u +%Y%m%d)

ifndef VIBE_BUILDTYPE
VIBE_BUILDTYPE := UNOFFICIAL
endif

VIBE_VERSION_SUFFIX := $(VIBE_BUILD_DATE)-$(VIBE_BUILDTYPE)-$(LINEAGE_BUILD)

VIBE_VERSION := $(VIBE_VERSION_MAJOR).$(VIBE_VERSION_MINOR)-$(VIBE_VERSION_SUFFIX)
VIBE_DISPLAY_VERSION := $(VIBE_VERSION_MAJOR).$(VIBE_VERSION_MINOR)

PRODUCT_PRODUCT_PROPERTIES += \
    ro.vibe.version=$(VIBE_VERSION) \
    ro.vibe.display.version=$(VIBE_DISPLAY_VERSION) \
    ro.vibe.build.version=$(VIBE_VERSION_MAJOR).$(VIBE_VERSION_MINOR) \
    ro.vibe.releasetype=$(VIBE_BUILDTYPE)
